### ISSUE TITLE
Deployment Filter latest Deployment slow

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#246]
AMW_rest/resources/deployments?appServerName=test&offset=0&onlyLatest=true
Old time: 1-2 s 
New time: 12-14 s

**Comment by polandy** [comment]
Hi Yves
I tried to reproduce the performance difference of factor 6-7 on my local machine without any success.
My results:
Release 1.14.0: 7.57s, 7.15s, 6.92s
Release 1.15.0: 6.74s, 6.78s, 6.95s
My conclusion is, that the performance of the specific request above on both releases is equivalent.
Did you make your measurements on the same environment?

**Comment by yvespp** [comment]
Yes, both numbers come from our production.
With which data did you test? We currently have about 270000 rows in tamw_deployment.

**Comment by wemu** [comment]
Hello

we request the latest deployment with the serverName and onlyLatest:
`/AMW_rest/resources/deployments?appServerName=censored&onlyLatest=true`

Some of these requests take up to 48 seconds. mainly "older" and active applications that have a lot of deployments. Most requests work normal but the more interesting ones with lots of deployments are way too slow (> 15s)

**Comment by yvespp** [comment]
Options:
* Check index on deployment table
* Check how many queries are caused by the left fetch that was added.
* Change from clob to varchar2 4000 for apps with version.

**Comment by polandy** [comment]
Hi Yves
I've analyzed the queries (1.14.0 and 1.15.0) which are generated by hibernate.
The Problem was not the new 'fetch' in the HQL but that a time-consuming count(*) was executed (and not necessary for the REST Call).
The branch "bugfix_246_avoid_count_for_paging_in_rest_call" avoids the call of the count(*) for the rest call.
The count() is only necessary for the which is only necessary for the paging.

The performance issue stays for the deployments site where the count is necessary. Here the result of my analysis:

The following query causes the performance issue for resourcegroups with more than 5'000 deployments:

`select  count(*)
from    TAMW_deployment d,
        TAMW_resourceGroup rg
where   d.resourceGroup_id = rg.id
and     d.deploymentDate=(
        select    max(d2.deploymentDate)
        from      TAMW_deployment d2
        where     d.resourceGroup_id=d2.resourceGroup_id
        and       d.context_id=d2.context_id
    )
    and (
        rg.name like '%RESOURCEGROUP_NAME%' escape '\'
    )
    ;`

In my environment there is a resourcegroup with more than 12'000 deployments. For this resourceGroup the query takes 23-24 seconds.
In average a resourceGroup has about 500 deployments.
For a resource group of 500 deployments the query takes 0.12s in my environment.
If we want to improve the performance for resourceGroups with more than 5'000 deployments we should analyze and improve the execution plan with a Oracle DBA.
Im my environment there are only 4 resourceGroups with more than 5'000 deployments.

**Comment by yvespp** [comment]
@wemu with release 1.15.2 the requests should be faster, can you please verify that?

**Comment by wemu** [comment]
hallo. the "onlyLatest" requests I make are way faster now! my "bad examples" are now below 120ms. Thanks a lot!
