### ISSUE TITLE
Document test setup

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#506]
* Document the java setup (e.g. lombok)
* Document how to run and test the JavaScript stuff locally.

**Comment by sdedijer** [comment]
Hi Yves,

For frontend we have junit tests and not yet e2e tests. On master branch junit can be started with
karma start
but once we move to the angular CLI then this will change. So maybe the best to wait until that point and then we can document it, is this ok for you?

Could you please tell us a little bit more details what do you want that we document. Some kind of summary in README which tells minimal requirements to run the app locally? Or maybe you wanted something else with java setup documentation?

Thanks a lot in advance for your reply.

**Comment by yvespp** [comment]
If you could just document the steps you took while setting up Liima on you PC for the first time that would be fine.

**Comment by sdedijer** [comment]
Hi Yves,

I have discussed a little bit with Robin and Max and we were thinking that for everybody else apart from us we can provide running the application easily and fast in docker (where we have wildfly app server and h2 db) and we also put Run Configuration which can be used in order to debug Liima Application Remotely on docker.
What is your opinion here, shall we do it like that? Or do you want that we document the same way like we did?
The reason why we decided to go for running liima in docker is because it will make it less complicated and faster. And the other problem is also that for us we have DB dump from prod and this data is for sure not something that we should publish.

I have just created pull request for this task so you can check it as well.

Thank you for your feedback in advance.
