### ISSUE TITLE
Simplify frontend setup

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#508]
* Reduce configuration
* Make updates simpler
* Cleanup old config
* Try to switch to angular cli

**Comment by mburri** [comment]
upgrading the dev dependencies with the current webpack config and edge cases (html-elements...) is not straight froward in any way. i was able to fix the build - everything compiles - but the app is still not working due to changes how htmlTemlplates are resolved and I was not able to fix it for now.

we should probably try to get rid of everything and proceed directly to angular-cli

**Comment by yvespp** [comment]
Closed with #512
