### ISSUE TITLE
Warning "Changes you made may not be saved." with default properties

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#513]
If a resource has default properties, the warning "Changes you made may not be saved." shows up after clicking save and trying to leave the page.
How to reproduce:
1. Create a new resource
1. Add a new property to the resource, set the default value to something. Click `Back to Edit Resource`
1. Click `Save changes` on the resource screen (no change need to made)
1. Click on the `Servers` tabs

Result: Liima shows the warning "Changes you made may not be saved." but no changes where made.
Only showed after upgrading Liima to JBoss EAP 7.2

**Comment by sdedijer** [comment]
Hi @yvespp ,

We have tried to reproduce this issue locally and we could not do it. But we are using Wildfly 12 locally and not EAP 7.2. Could you please check if you can reproduce it still with latest version of EAP that you use?

Thanks a lot in advance and BR!

**Comment by yvespp** [comment]
It still happens on 7.2.6 which ist the latest JBoss EAP Version.
What is important here is to click `Save changes` on the editResourceView screen, if you don't click save the message doesn't show up.

**Comment by yvespp** [comment]
I tried with the current master docker Image (liimaorg/liima:master) and I can reproduce it with that as well.

**Comment by mburri** [comment]
Issue is reproducable with 7.2.x , but not with Wildfly 12 and Wildfly 18

**Comment by mburri** [comment]
I pinned down the root cause of the issue.
To reproduced it, you just need to open a resource that has a property with a default value, click "save changes" and try to leave the page. This will not work when using jBoss EAP 7.2

The defaultValues of properties are stored in the DOM as the title attribute of the input element:
```
title="#{cc.attrs.property.propertyDefaultValue}"
```
see propertyEditor.xhtml, line 27

For jBoss EAP 7.2 this property is set on the initial page load. inspecting the element reveals this markup in the browser:

```html
<textarea
  id="j_idt187:j_idt188:8:j_idt200:j_idt203"
  name="j_idt187:j_idt188:8:j_idt200:j_idt203"
  class="propertyInputField upperContext changeAware oneLine rf-plhdr propertyplaceholder"
  onblur="setUpperContext(this, '', 'false'); validateInput(this, 'false', 'false', '.*', 'test3.3', ''); decorateInput(this, '', 'false', 'false');"
  onfocus="this.className = 'propertyInputField currentContext changeAware'"
  title="test3.3"
  onchange='RichFaces.ajax(this,event,{"sourceId":this,"parameters":{"javax.faces.behavior.event":"valueChange","org.richfaces.ajax.component":"j_idt187:j_idt188:8:j_idt200:j_idt203"} } )'
></textarea>
```
but after "save changes" - it looks like this:

```
<textarea
  id="j_idt187:j_idt188:8:j_idt200:j_idt203"
  name="j_idt187:j_idt188:8:j_idt200:j_idt203"
  class="propertyInputField upperContext changeAware oneLine rf-plhdr propertyplaceholder"
  onchange='RichFaces.ajax(this,event,{"sourceId":this,"parameters":{"javax.faces.behavior.event":"valueChange","org.richfaces.ajax.component":"j_idt187:j_idt188:8:j_idt200:j_idt203"} } )'
></textarea>
```
the properties onblur, onfocus and title are gone - the others are still there with the same values... 
this does *not* happen with Wildfly 12 or 18

It looks as if different views are rendered depending on the application container. This is probably caused by different provided dependencies...
