### ISSUE TITLE
Can't create new release on resources of type Applicationserver, Application or Node

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#98]
On the editResourceView screen the option `Release` -> `New` is missing on resources of type Applicationserver, Application or Node. `Change` and `Remove` are there. I have the config_admin role and it seems to have the right permissions: 
![image](https://user-images.githubusercontent.com/15231595/27229240-2282baf0-52ab-11e7-896d-2bcddf9a511b.png)

**Comment by RetGal** [comment]
#99 fixes this issue as well. The COPY_FROM_RESOURCE Permission is required for this. With the fix, the config_admin has this Permission for ANY ResourceType instead of NON_DEFAULT_ONLY.

![newrelease](https://user-images.githubusercontent.com/19471064/27575913-88b33886-5b1b-11e7-8ca9-78504cf1b015.png)
