### ISSUE TITLE
Permissions of config_admin role

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#99]
The role config_admin has wrong permissions after migration:
![image](https://user-images.githubusercontent.com/15231595/27231364-aeef57e4-52b2-11e7-8600-01c90388ba1e.png)

* COPY_FROM_RESOURCE UPDATE should by assigned to Res. Type Cat. ANY instead of NON_DEFAULT_ONLY
* RESOURCE CREATE/DELETE/UPDATE should by assigned to Res. Type Cat. ANY instead of NON_DEFAULT_ONLY
* RESOURCETYPE DELETE should by assigned to Res. Type Cat. ANY instead of NON_DEFAULT_ONLY
* RESOURCE UPDATE APPLICATION is not needed
* TEMPLATE_RESOURCETYPE CREATE ANY is missing

For RESOURCE, RESOURCETYPE and TEMPLATE_RESOURCETYPE the action ALL could be given instead of the individual actions.

We should maybe think about instead of migration the permissions to just define a default and let the users to their customization again. If you have to clean up the roles after the migration it is probably less work this way. Also with #97 the migration script will change drastically.

**Comment by yvespp** [comment]
Also config_admin can't update props on default resources:
![image](https://user-images.githubusercontent.com/15231595/27230972-4b8eacc8-52b1-11e7-9b5c-5145e2998058.png)

**Comment by RetGal** [comment]
Fixed:
-  COPY_FROM_RESOURCE UPDATE should by assigned to Res. Type Cat. ANY instead of NON_DEFAULT_ONLY
-  RESOURCE CREATE/DELETE/UPDATE should by assigned to Res. Type Cat. ANY instead of NON_DEFAULT_ONLY
-  RESOURCETYPE DELETE should by assigned to Res. Type Cat. ANY instead of NON_DEFAULT_ONLY
-  RESOURCE UPDATE APPLICATION is not needed
-  TEMPLATE_RESOURCETYPE CREATE ANY is missing

![config_admin](https://user-images.githubusercontent.com/19471064/27574228-c2991896-5b15-11e7-807a-8dec1f2f1f33.png)

**Comment by yvespp** [comment]
RESOURCETYPE UPDATE should also be set to all Res. Types

**Comment by RetGal** [comment]
RESOURCETYPE UPDATE set to ANY

**Comment by yvespp** [comment]
closed by #130
